theme: jekyll-theme-minimal
title: Open Source Project Codes of Conduct
logo: /assets/img/lifesaver.png
description: Your simple introduction to Codes of Conduct in FOSS Projects
show_downloads: false
google_analytics: UA-104072125-4

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary
social:
  name: Punderthings℠ LLC
  links:
    - http://punderthings.com/
    - http://shanecurcuru.org/

navbar:
  - title: "Project CoCs"
    url: "/projects"
  - title: "Reuseable CoCs"
    url: "/corecoc"
  - title: "More Resources"
    url: "/resources"

seealso:
  - title: "TL;DR Open Source"
    url: "http://tldropensource.com/"
    tag: "Simple explainers of common open source terms"
  - title: "Choose A Foundation"
    url: "http://chooseafoundation.com/"
    tag: "Guide to finding a FOSS Foundation for your project"
  - title: "Community Over Code"
    url: "communityovercode.com"
    tag: "Community-driven open source stories from Apache"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: true