remote_theme: ShaneCurcuru/minimalist-theme
title: Open Source Project Codes of Conduct
logo: /assets/img/lifesaver.png
description: Your simple introduction to Codes of Conduct in FOSS Projects
show_downloads: false
google_analytics: G-E0D53BG453
email: shane@punderthings.com
color-scheme: auto

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary
social:
  name: Punderthings℠ LLC
  links:
    - http://punderthings.com/
    - http://shanecurcuru.org/

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/ShaneCurcuru/
  - name: Project CoCs
    icon: <i class="fa-solid fa-pen"></i>
    link: /projects
  - name: Reuseable CoCs
    icon: <i class="fa-solid fa-pen"></i>
    link: /corecoc
  - name: More Resources
    icon: <i class="fa-solid fa-pen"></i>
    link: /resources

seealso:
  - title: "TL;DR Open Source"
    url: "http://tldropensource.com/"
    tag: "Simple explainers of common open source terms"
  - title: "Choose A Foundation"
    url: "http://chooseafoundation.com/"
    tag: "Guide to finding a FOSS Foundation for your project"
  - title: "Community Over Code"
    url: "communityovercode.com"
    tag: "Community-driven open source stories from Apache"

# See https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github: [metadata]