#!/usr/bin/env bash
echo "Building default liquid template from schema"
ruby ../SchemaUtils/lib/schema_utils.rb -i _data/cocpolicy-schema.json -o _includes/cocpolicy-fields.html -t _data/cocpolicy-template.md